version: '2'
services:
    web:
        image: tomcat
        ports:
            - 80:8080
        volumes:
            - ./MancalaApi/target/MancalaApi.war:/usr/local/tomcat/webapps/api.war
            - ./MancalaApi/target/MancalaApi:/usr/local/tomcat/webapps/api
            - ./MancalaWeb/target/MancalaWeb.war:/usr/local/tomcat/webapps/ROOT.war
            - ./MancalaWeb/target/MancalaWeb:/usr/local/tomcat/webapps/ROOT

    mongodb:
        image: mongo
